<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_controller</name>
  <version>0.0.0</version>
  <description>
  This package implements mapless, short-distance autonomous navigation 
  using FAST_LIO and Nav2. 
  It utilizes the real-time odometry and point cloud data generated 
  by FAST_LIO for the Nav2 stack.
  </description>
  <maintainer email="po7f9o3p@s.okayama-u.ac.jp">nomoto</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros2launch</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
